version: '2'
services:
  kafka:
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    image: spotify/kafka
  cassandra:
    image: cassandra:3.5
  spark:
    build: ./spark/.
    ports:
      - "9000:8080"
    volumes:
      - ./spark/.:/code/
    depends_on:
      - kafka
      - cassandra
  kafka_producer:
    build: ./kafka_producer/.
    volumes: 
      - ./kafka_producer:/code/
    command: python producer.py
    depends_on: 
      - kafka


